In [6]:
from __future__ import division
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv("../data/train.csv",nrows=10000)

In [3]:
df.columns

Index([u'id', u'click', u'hour', u'C1', u'banner_pos', u'site_id',
       u'site_domain', u'site_category', u'app_id', u'app_domain',
       u'app_category', u'device_id', u'device_ip', u'device_model',
       u'device_type', u'device_conn_type', u'C14', u'C15', u'C16', u'C17',
       u'C18', u'C19', u'C20', u'C21'],
      dtype='object')

In [4]:
df.head()

,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,1000009418151094273,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,2,15706,320,50,1722,0,35,-1,79
1,10000169349117863715,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
2,10000371904215119486,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
3,10000640724480838376,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15706,320,50,1722,0,35,100084,79
4,10000679056417042096,0,14102100,1005,1,fe8cc448,9166c161,0569f928,ecad2386,7801e8d9,...,1,0,18993,320,50,2161,0,35,-1,157

In [7]:
df['click'].sum()/len(df)

0.1706

In [10]:
len(df['app_domain'].unique())

31

In [12]:
byappdom = df.groupby(['app_domain', 'click'])

In [27]:
click_count_byapp = byappdom['id'].count()

In [42]:
df_click_count_byapp = click_count_byapp.unstack()

In [45]:
df_click_count_byapp[2:].head()

click         0   1
app_domain
18eb4e75      2 NaN
2347f47a    634  72
33da2e74     15   4
3feeed1e      1 NaN
43cf4f06      5 NaN

In [39]:
df_click_count_byapp['freq'] = df_click_count_byapp[[0, 1]].apply(lambda x: x)

In [41]:
df_click_count_byapp

click          0     1  freq
app_domain
0654b444      26     6    26
15ec7f39       1   NaN     1
18eb4e75       2   NaN     2
2347f47a     634    72   634
33da2e74      15     4    15
3feeed1e       1   NaN     1
43cf4f06       5   NaN     5
45a51db4     101    15   101
5ac0b939       1   NaN     1
5b9c592b      10   NaN    10
5c5a694b     150    38   150
5c620f04       8   NaN     8
6f7ca2ba       2   NaN     2
7801e8d9    6776  1530  6776
813f3323       5   NaN     5
82e27996     228     8   228
885c7f3f      17     5    17
ad63ec9b       7   NaN     7
ae637522      34     2    34
aefc06bd      52     6    52
afdf1f54       1   NaN     1
b5f3b24a       6   NaN     6
b8d325c3       1   NaN     1
b9528b13      15     1    15
c6824def       6   NaN     6
d9b5648e     182    17   182
db829551       1   NaN     1
df32afa9       1     1     1
e787a6bc       2   NaN     2
f2f777fb       3     1     3
f3ad7798       1   NaN     1

In [52]:
pieces = dict(list(df.groupby(['click','app_domain'])))

In [57]:
df.groupby(['click','app_domain'])['id'].count()

click  app_domain
0      0654b444        26
       15ec7f39         1
       18eb4e75         2
       2347f47a       634
       33da2e74        15
       3feeed1e         1
       43cf4f06         5
       45a51db4       101
       5ac0b939         1
       5b9c592b        10
       5c5a694b       150
       5c620f04         8
       6f7ca2ba         2
       7801e8d9      6776
       813f3323         5
       82e27996       228
       885c7f3f        17
       ad63ec9b         7
       ae637522        34
       aefc06bd        52
       afdf1f54         1
       b5f3b24a         6
       b8d325c3         1
       b9528b13        15
       c6824def         6
       d9b5648e       182
       db829551         1
       df32afa9         1
       e787a6bc         2
       f2f777fb         3
       f3ad7798         1
1      0654b444         6
       2347f47a        72
       33da2e74         4
       45a51db4        15
       5c5a694b        38
       7801e8d9      1530
       82e27996         8
       885c7f3f         5
       ae637522         2
       aefc06bd         6
       b9528b13         1
       d9b5648e        17
       df32afa9         1
       f2f777fb         1
Name: id, dtype: int64

In [59]:
clicked_byapp = df[df['click']==1].groupby('app_domain')
notclicked_byapp = df[df['click']==0].groupby('app_domain')

In [61]:
clicked_byapp['id'].count()

app_domain
0654b444       6
2347f47a      72
33da2e74       4
45a51db4      15
5c5a694b      38
7801e8d9    1530
82e27996       8
885c7f3f       5
ae637522       2
aefc06bd       6
b9528b13       1
d9b5648e      17
df32afa9       1
f2f777fb       1
Name: id, dtype: int64

In [63]:
notclicked_byapp['id'].count()

app_domain
0654b444      26
15ec7f39       1
18eb4e75       2
2347f47a     634
33da2e74      15
3feeed1e       1
43cf4f06       5
45a51db4     101
5ac0b939       1
5b9c592b      10
5c5a694b     150
5c620f04       8
6f7ca2ba       2
7801e8d9    6776
813f3323       5
82e27996     228
885c7f3f      17
ad63ec9b       7
ae637522      34
aefc06bd      52
afdf1f54       1
b5f3b24a       6
b8d325c3       1
b9528b13      15
c6824def       6
d9b5648e     182
db829551       1
df32afa9       1
e787a6bc       2
f2f777fb       3
f3ad7798       1
Name: id, dtype: int64

In [64]:
pd.concat([clicked_byapp['id'].count(), notclicked_byapp['id'].count()])

app_domain
0654b444       6
2347f47a      72
33da2e74       4
45a51db4      15
5c5a694b      38
7801e8d9    1530
82e27996       8
885c7f3f       5
ae637522       2
aefc06bd       6
b9528b13       1
d9b5648e      17
df32afa9       1
f2f777fb       1
0654b444      26
15ec7f39       1
18eb4e75       2
2347f47a     634
33da2e74      15
3feeed1e       1
43cf4f06       5
45a51db4     101
5ac0b939       1
5b9c592b      10
5c5a694b     150
5c620f04       8
6f7ca2ba       2
7801e8d9    6776
813f3323       5
82e27996     228
885c7f3f      17
ad63ec9b       7
ae637522      34
aefc06bd      52
afdf1f54       1
b5f3b24a       6
b8d325c3       1
b9528b13      15
c6824def       6
d9b5648e     182
db829551       1
df32afa9       1
e787a6bc       2
f2f777fb       3
f3ad7798       1
Name: id, dtype: int64

In [68]:
df1 = pd.DataFrame(dict(clicked=clicked_byapp['id'].count(), notclicked = notclicked_byapp['id'].count()))

In [73]:
df1.fillna(0, inplace=True)

In [70]:
df1['success'] = df1.clicked/(df1.notclicked + df1.clicked)

In [74]:
df1

          clicked  notclicked   success
0654b444        6          26  0.187500
15ec7f39        0           1  0.000000
18eb4e75        0           2  0.000000
2347f47a       72         634  0.101983
33da2e74        4          15  0.210526
3feeed1e        0           1  0.000000
43cf4f06        0           5  0.000000
45a51db4       15         101  0.129310
5ac0b939        0           1  0.000000
5b9c592b        0          10  0.000000
5c5a694b       38         150  0.202128
5c620f04        0           8  0.000000
6f7ca2ba        0           2  0.000000
7801e8d9     1530        6776  0.184204
813f3323        0           5  0.000000
82e27996        8         228  0.033898
885c7f3f        5          17  0.227273
ad63ec9b        0           7  0.000000
ae637522        2          34  0.055556
aefc06bd        6          52  0.103448
afdf1f54        0           1  0.000000
b5f3b24a        0           6  0.000000
b8d325c3        0           1  0.000000
b9528b13        1          15  0.062500
c6824def        0           6  0.000000
d9b5648e       17         182  0.085427
db829551        0           1  0.000000
df32afa9        1           1  0.500000
e787a6bc        0           2  0.000000
f2f777fb        1           3  0.250000
f3ad7798        0           1  0.000000

In [75]:
df1.sort('success', inplace=True)

In [76]:
df1

          clicked  notclicked   success
f3ad7798        0           1  0.000000
813f3323        0           5  0.000000
b5f3b24a        0           6  0.000000
6f7ca2ba        0           2  0.000000
5c620f04        0           8  0.000000
b8d325c3        0           1  0.000000
5b9c592b        0          10  0.000000
afdf1f54        0           1  0.000000
5ac0b939        0           1  0.000000
43cf4f06        0           5  0.000000
3feeed1e        0           1  0.000000
db829551        0           1  0.000000
e787a6bc        0           2  0.000000
18eb4e75        0           2  0.000000
15ec7f39        0           1  0.000000
c6824def        0           6  0.000000
ad63ec9b        0           7  0.000000
82e27996        8         228  0.033898
ae637522        2          34  0.055556
b9528b13        1          15  0.062500
d9b5648e       17         182  0.085427
2347f47a       72         634  0.101983
aefc06bd        6          52  0.103448
45a51db4       15         101  0.129310
7801e8d9     1530        6776  0.184204
0654b444        6          26  0.187500
5c5a694b       38         150  0.202128
33da2e74        4          15  0.210526
885c7f3f        5          17  0.227273
f2f777fb        1           3  0.250000
df32afa9        1           1  0.500000